services:
  frontend:
    image: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:5600/
    volumes:
      - "../frontend/:/app:delegated"
      - /app/node_modules

  backend:
    image: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5600:5600"
    environment:
      - PORT=5600
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/hackathon
      - NODE_ENV=development
      - SESSION_SECRET=secret
      - SESSION_MAX_AGE=1440
      - FRONTEND_URL=http://localhost:5173
      - REDIS_URL=redis://redis:6379
    volumes:
      - "../backend/:/app"
      - /app/node_modules

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hackathon
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: